name: check markdown style

on: 
  pull_request:
    paths:
      - '**.md'

jobs:
  mdlint:
    name: mdlint
    runs-on: ubuntu-latest
    steps:
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: "**/*.md"
        config_file: ".markdownlint.json"
